name: Pickup
main: org.retrohaven.pickup.Pickup
version: 1.0
description: Allows players to mine and pickup unobtainable blocks.
author: Lilly (retrorandom)

commands:
  setspawner:
    description: Sets the mob type for a spawner. OPs can change other players' spawners.
    usage: /setspawner <mob> [player]
    permission: spawnerpickup.setspawner
    aliases: [spawnerchange, spawneredit]

permissions:
  pickup.use:
    description: Allows breaking spawners with a golden pickaxe.
    default: op
  pickup.setspawner:
    description: Allows changing mob spawner type.
    default: op
  pickup.setspawner.others:
    description: Allows changing other players' mob spawner type.
    default: op