name: SpawnerPickup
main: com.retrohaven.spawnerpickup.SpawnerPickup
version: 1.0
description: Allows players to mine spawners with a golden pickaxe and change spawner mobs.
author: Lilly E (retrorandom)

commands:
  setspawner:
    description: Sets the mob type for a spawner. OPs can change other players' spawners.
    usage: /setspawner <mob> [player]
    permission: spawnerpickup.setspawner
    aliases: [spawnerchange, spawneredit]

permissions:
  spawnerpickup.use:
    description: Allows breaking spawners with a golden pickaxe.
    default: op
  spawnerpickup.setspawner:
    description: Allows changing mob spawner type.
    default: op
  spawnerpickup.setspawner.others:
    description: Allows changing other players' mob spawner type.
    default: op